[project]
name="src"
version="0.0.1"
description="A MLOps project for productioning model"
authors=[{name="Kunal Koshta",email="harhskosh200407@gmail.com"}]

[tool.setuptools]
packages = {find = {} }

[tool.setuptools.dynamic]
dependencies = {file = 'requirements.txt'}